# Generated by Django 3.1.2 on 2020-11-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id_book', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('genre', models.IntegerField(blank=True, null=True)),
                ('year_create', models.DateField(blank=True, null=True)),
                ('price_book', models.IntegerField(blank=True, null=True)),
                ('rate', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id_genre', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_genre', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'genre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LendingBooks',
            fields=[
                ('code_lend', models.IntegerField(primary_key=True, serialize=False)),
                ('id_librarian', models.IntegerField(blank=True, null=True)),
                ('book', models.IntegerField(blank=True, null=True)),
                ('reader', models.IntegerField(blank=True, null=True)),
                ('date_lend', models.DateField(blank=True, null=True)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('sum_fine', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lending_books',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('family_lib', models.CharField(blank=True, max_length=50, null=True)),
                ('name_lib', models.CharField(blank=True, max_length=50, null=True)),
                ('patronymic_lib', models.CharField(blank=True, max_length=50, null=True)),
                ('exp', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'librarian',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('family_read', models.CharField(blank=True, max_length=50, null=True)),
                ('name_read', models.CharField(blank=True, max_length=50, null=True)),
                ('patronymic_lib', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('num_mobile', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'reader',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SystemFine',
            fields=[
                ('id_fine', models.BigAutoField(primary_key=True, serialize=False)),
                ('fault_damage', models.CharField(blank=True, max_length=50, null=True)),
                ('sum_fine', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'system_fine',
                'managed': False,
            },
        ),
    ]
